name = "Sparky"                                                         
dynamic = true                                                          

[orbit]                                                                
semimajor_axis = 4.2
eccentricity = 0.7
inclination = 63.4
raan = 30.0
arg_perigee = 270.0
true_anomaly = 0.0
