name = "Sparky"                                                         
dynamic = true                                                          
dt = 0.1
tfactor = 200.0
text_refresh = 0.5

gravity_model = "j2"

ref_point_lat_lon_alt = [40.0, -80.0, 0.0]

[orbit]                                                                
semimajor_axis = 1.1
eccentricity = 0.001
inclination = 63.4
raan = 30.0
arg_perigee = 270.0
true_anomaly = 0.0
