name = "Sparky"                                                         
dynamic = false

[orbit]                                                                
semimajor_axis = 0.0
eccentricity = 0.0
inclination = 0.0
raan = 0.0
arg_perigee = 0.0
true_anomaly = 0.0
