name = "Sparky"                                                         
dynamic = true                                                          
dt = 0.1
tfactor = 1000.0
text_refresh = 0.5
model_scale = 5

gravity_model = "j2"

ref_point_lat_lon_alt = [40.0, -80.0, 0.0]

[orbit]                                                                
semimajor_axis = 4.2
eccentricity = 0.7
inclination = 63.4
raan = 30.0
arg_perigee = 270.0
true_anomaly = 0.0

#[struct]
#weight = 39000.0
#jxx = 25000.0
#jyy = 122200.0
#jzz = 139800.0
#jxy = 0.0
#jxz = 2200.0
#jyz = 0.0

#[prop]
#thrust = 39000.0

